live:
- name: Ethereum
  networks:
  - chainid: 534353
    explorer: https://blockscout.scroll.io/
    host: https://scroll-alphanet.public.blastapi.io
    id: testnet-scroll
    name: Testnet (scroll)